### ISSUE TITLE
What version of Tensorflow the code runs with?

### ISSUE THREAD

**Issue by Crista23** [dongjun-Lee/text-classification-models-tf#7]
It crashes in Tensorflow 1.4 with the error below:

Traceback (most recent call last):
  File "train.py", line 47, in <module>
    model = VDCNN(alphabet_size, CHAR_MAX_LEN, NUM_CLASS)
  File "text-classification-models-tf/cnn_models/vd_cnn.py", line 70, in __init__
    tf.nn.softmax_cross_entropy_with_logits_v2(logits=self.logits, labels=y_one_hot))
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'softmax_cross_entropy_with_logits_v2'

**Comment by grapeff** [comment]
I have the same problem.
